// Response constants

export const RESPONSE_CODES = {
    SUCCESS: "SUCCESS",
    ERROR: "ERROR",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    NOT_FOUND: "NOT_FOUND",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    EXPIRED: "EXPIRED",
    ALREADY_EXISTS: "ALREADY_EXISTS",
    INVALID_TOKEN: "INVALID_TOKEN",
    INVITATION_EXPIRED: "INVITATION_EXPIRED",
    INVITATION_ALREADY_USED: "INVITATION_ALREADY_USED",
} as const;
