name: Build and deploy Node.js app to Azure Web App - employeeapi25

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test in api/
        working-directory: ./api
        run: |
          npm install --legacy-peer-deps
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment (api only)
        run: zip -r release.zip ./api

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-api-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-api-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2F6330101D7B4F5594B6D6D38D129285 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ED1E765701D14587A2EB9342E90526C7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D62EEE627F264969B2CAF2D8C33541DF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'employeeapi25'
          slot-name: 'Production'
          package: ./api
